name: Run CHOpt_linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-chopt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Make CHOpt_linux executable
      run: chmod +x ./CHOpt_linux

    - name: Run Python script to execute CHOpt_linux
      run: |
        python3 run_chopt_linux.py

    - name: List files for debugging
      run: ls -la test

    - name: Commit and push .txt file (ignore CHOpt_linux changes)
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git restore --staged CHOpt_linux # Ensure we don't stage changes to the executable
        git add test/output.txt
        git commit -m "Add CHOpt_linux output.txt"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}