name: Run CHOpt and Commit Output

on:
  push:
    branches:
      - main  # Change to your target branch if needed

jobs:
  run-chopt:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you want to use

      - name: Make CHOpt executable
        run: |
          chmod +x ./CHOpt  # Ensure CHOpt is executable
          chmod +x ./libpng16.16.dylib 

      - name: Run CHOpt
        run: |
          ./CHOpt -f notes.mid > output.txt 2>&1

      - name: Commit output.txt
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output.txt'
          message: 'Add output.txt from CHOpt run'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'          